# Базовый образ
FROM python:3.12-slim

# Переменные окружения
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Рабочая директория
WORKDIR /app

# Устанавливаем зависимости
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Устанавливаем PostgreSQL client для pg_isready
RUN apt-get update && apt-get install -y postgresql-client && rm -rf /var/lib/apt/lists/*

# Копируем проект
COPY . .

# Создаем директорию для логов
RUN mkdir -p /app/logs
RUN mkdir -p /app/staticfiles /app/media

# Устанавливаем права (опционально)
RUN chmod -R 755 /app