# Generated by Django 4.2 on 2025-09-08 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_quotes', '0002_alter_quote_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
