# Generated by Django 4.2 on 2025-09-08 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_quotes', '0003_quote_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='quantity',
        ),
    ]
